version: 2
updates:
  # Maintain dependencies for Python in setup.py and requirements.txt
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "master"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"
    # Group dependencies into single PR
    groups:
      development-dependencies:
        patterns:
          - "black"
          - "flake8*"
          - "isort"
          - "mypy"
          - "pylint"
          - "pytest*"
          - "bandit"
        update-types:
          - "minor"
          - "patch"
    # Custom versioning strategy
    versioning-strategy:
      # Use the version specified in the package to determine the new version
      increase-if-necessary: false
      # Using lockfile to ensure both requirements.txt and setup.py stay in sync
      lockfile-only: false
      # Update package versions in setup.py to match
      widen: false
      # Update all dependencies, not just direct ones
      update-dependency-type: "all"
    # Ignore specific updates that have known conflicts
    ignore:
      # Ignore cachetools 6.x until google-auth supports it
      # google-auth 2.40.3 requires cachetools<6.0,>=2.0.0
      - dependency-name: "cachetools"
        versions: ["6.x"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"
