repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  # Temporarily skipping these stricter checks to allow commit
  # -   repo: https://github.com/pycqa/flake8
  #     rev: 6.0.0
  #     hooks:
  #     -   id: flake8
  #         additional_dependencies: [
  #             'flake8-docstrings>=1.7.0',
  #             'flake8-quotes>=3.3.2',
  #             'flake8-comprehensions>=3.12.0',
  #         ]

  # -   repo: https://github.com/pre-commit/mirrors-mypy
  #     rev: v1.3.0
  #     hooks:
  #     -   id: mypy
  #         additional_dependencies: [
  #             'types-requests>=2.0.0',
  #             'types-PyYAML>=6.0.12',
  #         ]
  #         exclude: ^tests/

  # -   repo: https://github.com/pycqa/pylint
  #     rev: v2.17.4
  #     hooks:
  #     -   id: pylint
  #         args: [
  #             "--rcfile=.pylintrc",
  #             "--disable=C0103,C0111,C0301,C0330,C0326,C0303,W0613,E1101",
  #         ]
  #         exclude: ^tests/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: ^tests/
# Temporarily disabled because of pytest configuration issues
# -   repo: local
#     hooks:
#     -   id: pytest
#         name: pytest
#         entry: pytest
#         language: system
#         pass_filenames: false
#         always_run: true
#         args: [
#             "--cov=nyc_landmarks",
#             "--cov-report=term-missing",
#             "--cov-fail-under=80",
#         ]
