---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-merge-conflict

  # Enhanced secret detection for API keys, tokens, and credentials
  - repo: local
    hooks:
      - id: gitleaks-scan
        name: Detect secrets, API keys, and tokens
        description: Detect secrets, API keys, and credentials in all files including documentation
        entry: bash -c 'gitleaks detect --source=. --config=.gitleaks.toml --no-git --exit-code=2 || (echo "❌ Secrets detected! Please review and remove any exposed API keys, tokens, or credentials." && exit 1)'
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length", "88"]
        files: ^(scripts|nyc_landmarks|tests|utils)/.*\.py$

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2 # or latest
    hooks:
      - id: autopep8
        args: ["--select=E225,E226,E302,E305", "--in-place"]
        files: ^(scripts|nyc_landmarks|tests|utils)/.*\.py$|^test_.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
          ]
        files: ^(scripts|nyc_landmarks|tests|utils)/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-quotes
          - flake8-comprehensions

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        args: ["--config-file=mypy.ini", "--disable-error-code=misc"]
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-tabulate

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright
        args: ["--project", "pyrightconfig-precommit.json"]
        additional_dependencies:
          - types-requests==2.32.0.20250328
          - types-PyYAML
          - types-tabulate
          - pydantic==2.11.4
          - pydantic-settings==2.9.1
          - requests==2.32.3

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        exclude: ^tests/
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7 # Use the latest version
    hooks:
      - id: actionlint

  # Custom hook for Dockerfile linting with hadolint
  - repo: local
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles with hadolint (Docker)
        description: Runs hadolint Docker image to lint Dockerfiles
        language: system
        entry: bash -c 'if [ -f "Dockerfile" ]; then docker run --rm -i hadolint/hadolint < Dockerfile || true; fi'
        files: ^Dockerfile$
        pass_filenames: false

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        name: Format Markdown files with mdformat
        description: Auto-formats Markdown files for consistency
        additional_dependencies:
          - mdformat-gfm==0.4.1 # GitHub-Flavored Markdown support
          - mdformat-black==0.1.1 # For code blocks
          - mdformat-frontmatter==2.0.8 # For YAML frontmatter
          - mdformat-footnote==0.1.1 # For footnote support
        files: \.(md|markdown)$
        exclude: ^(venv|\.venv|env|ENV|\.pytest_cache|\.gcp|\.terraform|\.scannerwork|\.sonarlint|output|logs|temp|test_output|temp_notebooks|verification_results|pinecone_backup|build|dist|\.eggs)/.*$
        args: ["--wrap", "keep"]

  # Jupyter notebook output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        files: ".ipynb$"

  # Jupyter notebook linting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
        args: ["--line-length=88"]
      - id: nbqa-isort
        args: ["--profile=black", "--filter-files"]
      - id: nbqa-flake8
        args:
          [
            "--extend-ignore=E203,E501,F401,F541,W293,C901,F821,E226,E741,C401,F811",
            "--max-line-length=100",
          ]
        additional_dependencies:
          - flake8-docstrings
          - flake8-quotes
          - flake8-comprehensions

  # Custom hook to initialize Terraform modules before validation
  - repo: local
    hooks:
      - id: terraform-init-modules
        name: Initialize Terraform modules
        description: Initialize all Terraform modules before validation
        entry: bash -c 'find . -name "*.tf" -exec dirname {} \; | sort -u | xargs -I {} sh -c "cd \"{}\" && if [ -f versions.tf ] || [ -f main.tf ]; then terraform init -backend=false >/dev/null 2>&1 || true; fi" && exit 0'
        language: system
        files: (\.tf|\.tfvars)$
        pass_filenames: false
        always_run: false

  # Terraform validation and formatting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
    hooks:
      - id: terraform_fmt
        name: Terraform format
        description: Rewrites all Terraform configuration files to a canonical format
        files: (\.tf|\.tfvars)$

      - id: terraform_validate
        name: Terraform validate
        description: Validates all Terraform configuration files
        files: (\.tf|\.tfvars)$
        args:
          - --args=-no-color
          - --hook-config=--retry-once-with-cleanup=true
