name: Dependency Review

on:
  pull_request:
    branches: [master]
    paths:
      - 'requirements.txt'
      - 'setup.py'
      - '.github/workflows/**'

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          deny-licenses: 'GPL-3.0, AGPL-3.0'
          fail-on-severity: 'high'

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run security scan with Bandit
        run: bandit -r nyc_landmarks/ -f sarif -o bandit-results.sarif || true

      - name: Check for vulnerable dependencies
        run: safety check -r requirements.txt || true

      - name: Upload security scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-results.sarif
