name: Sync Package Versions

on:
  pull_request:
    paths:
      - "requirements.txt"
    types: [opened, synchronize]

jobs:
  sync-versions:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Run version synchronization script
        run: |
          ./scripts/ci/sync_versions.sh

      - name: Check if changes were made
        id: git-check
        run: |
          git diff --exit-code setup.py || echo "changes=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add setup.py
          git commit -m "Sync package versions between setup.py and requirements.txt"
          git push
