name: Sync Package Versions

on:
  pull_request:
    paths:
      - "requirements.txt"
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  sync-versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Run version synchronization script
        id: sync
        run: |
          if ./scripts/ci/sync_versions.sh; then
            echo "sync_completed=true" >> "$GITHUB_OUTPUT"
          else
            echo "sync_completed=false" >> "$GITHUB_OUTPUT"
            exit 1
          fi

      - name: Check if changes were made
        id: git-check
        run: |
          git diff --exit-code setup.py || echo "changes=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true' && steps.sync.outputs.sync_completed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add setup.py
          git commit -m "Sync package versions between setup.py and requirements.txt"
          git push
